// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD13a3XdlvHyztsH7BrHwN0ZWJHchGEdLU',
    appId: '1:890604729467:web:b95a063003ee68ca659ede',
    messagingSenderId: '890604729467',
    projectId: 'access-car-boot',
    authDomain: 'access-car-boot.firebaseapp.com',
    databaseURL: 'https://access-car-boot-default-rtdb.firebaseio.com',
    storageBucket: 'access-car-boot.appspot.com',
    measurementId: 'G-7JM0BYT734',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-dZpCmXHSUER81vDJCxUflWnFX6piJAM',
    appId: '1:890604729467:android:fd560489e9f95c2a659ede',
    messagingSenderId: '890604729467',
    projectId: 'access-car-boot',
    databaseURL: 'https://access-car-boot-default-rtdb.firebaseio.com',
    storageBucket: 'access-car-boot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTfVRYB8Oh5DgwMG1GXwzv4M-pJH_E-AI',
    appId: '1:890604729467:ios:31936228dcdca9eb659ede',
    messagingSenderId: '890604729467',
    projectId: 'access-car-boot',
    databaseURL: 'https://access-car-boot-default-rtdb.firebaseio.com',
    storageBucket: 'access-car-boot.appspot.com',
    iosBundleId: 'com.clone.cba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTfVRYB8Oh5DgwMG1GXwzv4M-pJH_E-AI',
    appId: '1:890604729467:ios:548a3450db24c8dc659ede',
    messagingSenderId: '890604729467',
    projectId: 'access-car-boot',
    databaseURL: 'https://access-car-boot-default-rtdb.firebaseio.com',
    storageBucket: 'access-car-boot.appspot.com',
    iosBundleId: 'com.clone.cba.RunnerTests',
  );
}
